Fix compilation errors in UI tests
redhat-developer/vscode-project-initializer pull request #59
Opened 2020-10-12 13:26 UTC by odockal

Fixes #58.
Signed-off-by: Ondrej Dockal <odockal@redhat.com>

2020-10-12 13:36 UTC, jeffmaury requested changes
It's getting better but I think there are still UI tests failing because some stack may have been removed

2020-10-12 20:29 UTC, odockal commented
@jeffmaury Nope, depends on the size of VSCode window there could be limit to the actual size of the quick picks (versions) showed. Scroll bar is introduced.

2020-10-13 21:03 UTC, odockal commented
@jeffmaury seems to be fixed.

2020-10-14 05:59 UTC, jeffmaury approved these changes

2020-10-14 05:59 UTC, merged