Add telemetry
redhat-developer/vscode-project-initializer pull request #64
Opened 2021-02-05 10:58 UTC by jeffmaury

Fixes #63

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

2021-02-05 14:49 UTC, jeffmaury commented
@odockal @jrichter1 any clue with UI tests are failing ?

2021-02-11 20:43 UTC, odockal commented
@jeffmaury Builds on Travis were disabled due to "negativa credit balance" on public repos. So I think that removing travis is quite necessary.

2021-02-12 05:32 UTC, dgolovin requested changes

2021-02-12 05:32 UTC, dgolovin commented on package.json
> +        "@redhat-developer/vscode-redhat-telemetry": "0.0.11"
Update telemetry module to 0.0.13.

2021-02-12 05:32 UTC, dgolovin commented on src/extension.ts
> +        telemetryProps.error = error.toString();
make sure that user sensitive information cannot leak through exception message. For example `catalogBuilder.zip` method could fail and have local path reported as part of the exception's message.

2021-02-17 12:52 UTC, jeffmaury commented
Replaced by #68

2021-02-18 14:14 UTC, merged